export const kitchenMeasurementTypes = [
  {value: 'c', label: 'Cup'},
  {value: 'fl. oz.', label: 'Fluid Ounce'},
  {value: 'gal', label: 'Gallon'},
  {value: 'g', label: 'Gram'},
  {value: 'kg',  label: 'Kilogram'},
  {value: 'l', label: 'Liter'},
  {value: 'mL', label: 'Milliliter'},
  {value: 'oz', label: 'Ounce'},
  {value: 'pcs', label: 'Pieces'},
  {value: 'pt', label: 'Pint'},
  {value: 'lb', label: 'Pound'},
  {value: 'qt', label: 'Quart'},
  {value: 'tbsp', label: 'Tablespoon'},
  {value: 'tsp', label: 'Teaspoon'},
]